package net.minestom.data;

import java.io.InputStream;

/**
 * Autogenerated data derived from <a href="https://github.com/Minestom/MinestomDataGenerator">MinestomDataGenerator</a>
 */
@SuppressWarnings("unused")
public final class MinestomData {
    private static final String COMMIT = "&COMMIT";
    private static final String BRANCH = "&BRANCH";

    public static String commit() { return COMMIT; }
    public static String branch() { return BRANCH; }

    /**
     * Gets a resource from the data module.
     *
     * @param path the path (relative to /net/minestom/data)
     * @return the resource from the data module, or null
     */
    public static InputStream resource(String path) {
        // Required to execute here as getModule() returns this module
        // Otherwise would fail cause of encapsulation or would require opens.
        return MinestomData.class.getResourceAsStream(path);
    }

    private MinestomData() {}
}
